export { default as ViewTrucks } from './view-trucks'
export { default as ViewAllTrucks } from './viewall-truck.js'
export { default as ImportTruk } from './import-truk.js'
export { default as BulkCreateTruk } from './bulk-create-truk.js'
export { default as BulkUpdateTruk } from './bulk-update-truk.js'
